name: Continuous Integration

on:
  
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Install APT dependencies
      run: sudo apt install build-essential cmake python pip

    - name: Install conan
      run: pip install conan

    - name: Build tests
      run: |
        cmake -DBUILD_TESTING=ON .
        make
        
    - name: Run tests
      run: ./EuclideanTest
