name: Continuous Integration

on:
  
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest
    steps:
    
    - name: Install APT dependencies
      run: sudo apt install build-essential cmake python pip

    - name: Install conan
      run: pip install conan

    - name: Configure conan compiler
      run: |
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: conan install .

    - name: Build tests
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=conan/conan_toolchain.cmake -DBUILD_TESTING=ON .
        make
        
    - name: Run tests
      run: ~/work/Euclidean/Euclidean/bin/EuclideanTest
