name: Continuous Integration

on:
  
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest
    steps:
    
    - name: Install APT dependencies
      run: sudo apt install build-essential cmake python pip catch2

    - uses: actions/checkout@v2

    - name: Build tests
      run: |
        cmake -DBUILD_TESTING=ON .
        make
        
    - name: Run tests
      run: ~/work/Euclidean/Euclidean/bin/EuclideanTest
