name: Continuous Integration

on:
  
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  test:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Install APT dependencies
      run: sudo apt install build-essential cmake

    - name: Cache Google Test
      id: cache-gtest
      uses: actions/cache@v2
      with:
        path: |
          /usr/include/gtest
          /usr/lib/libgtest.a
          /usr/lib/libgtest_main.a
        key: ${{ runner.os }}-gtest

    - name: Install Google Test
      if: steps.cache-gtest.outputs.cache-hit != 'true'
      run: |
        sudo apt install libgtest-dev
        cd /usr/src/googletest
        sudo cmake .
        sudo cmake --build . --target install
        
    - name: Build tests
      run: |
        cmake -DBUILD_TESTING=ON .
        make
        
    - name: Run tests
      run: ./EuclideanTest
